[connections.myconnection]
account = "${SNOWFLAKE_CONNECTIONS_MYCONNECTION_ACCOUNT}"
user = "${SNOWFLAKE_CONNECTIONS_MYCONNECTION_USER}"
private_key = "${SNOWFLAKE_CONNECTIONS_MYCONNECTION_PRIVATE_KEY_RAW}"
authenticator = "SNOWFLAKE_JWT"
database = "${SNOWFLAKE_CONNECTIONS_MYCONNECTION_DATABASE}"
warehouse = "${SNOWFLAKE_CONNECTIONS_MYCONNECTION_WAREHOUSE}"

[connections.devconnection]
account = "${SNOWFLAKE_CONNECTIONS_DEVCONNECTION_ACCOUNT}"
user = "${SNOWFLAKE_CONNECTIONS_DEVCONNECTION_USER}"
private_key = "${SNOWFLAKE_CONNECTIONS_DEVCONNECTION_PRIVATE_KEY_RAW}"
authenticator = "SNOWFLAKE_JWT"
database = "${SNOWFLAKE_CONNECTIONS_DEVCONNECTION_DATABASE}"
warehouse = "${SNOWFLAKE_CONNECTIONS_DEVCONNECTION_WAREHOUSE}"

[connections.preprodconnection]
account = "${SNOWFLAKE_CONNECTIONS_PREPRODCONNECTION_ACCOUNT}"
user = "${SNOWFLAKE_CONNECTIONS_PREPRODCONNECTION_USER}"
private_key = "${SNOWFLAKE_CONNECTIONS_PREPRODCONNECTION_PRIVATE_KEY_RAW}"
authenticator = "SNOWFLAKE_JWT"
database = "${SNOWFLAKE_CONNECTIONS_PREPRODCONNECTION_DATABASE}"
warehouse = "${SNOWFLAKE_CONNECTIONS_PREPRODCONNECTION_WAREHOUSE}"